export const Head = () => {
  return (
    <>
      <h1 className='text-center text-6xl text-white/60'>Lexica API</h1>
      <span className='text-center block font-normal text-xl lg:text-2xl text-white/60 mt-5  leading-1'>
        The Stable Diffusion search engine.
      </span>
      <span className='text-center block font-normal  text-xl lg:text-2xl text-white/60 leading-none'>
        Images generated by AI.
      </span>
    </>
  )
}
